Update
bash: fzf shell integration, simplify bashrc
scripts: Simplify and refactor
neovim: Use fzf-lua instead of telescope

diff --git a/configs/bash/bashrc b/configs/bash/bashrc
--- a/configs/bash/bashrc
+++ b/configs/bash/bashrc
@@ -7,12 +7,121 @@ export MY_DOTFILES_REPO=${HOME}/misc/dotfiles
 [[ $- != *i* ]] && return
 
 # Stop here if the dotfiles repo was not found
-if [ ! -d "${MY_DOTFILES_REPO}" ]; then
-    echo "dotfiles repo not found"
-    return
-fi
+[ ! -d "${MY_DOTFILES_REPO}" ] && echo "dotfiles repo not found" && return
 
-source "${MY_DOTFILES_REPO}/configs/bash/aliases"
-source "${MY_DOTFILES_REPO}/configs/bash/variables"
-source "${MY_DOTFILES_REPO}/configs/bash/functions"
-source "${MY_DOTFILES_REPO}/configs/bash/completions"
+# Default arguments
+alias cp='cp --verbose --interactive'
+alias mv='mv --verbose --interactive'
+alias rm='rm --verbose --interactive=once'
+alias rg='rg --smart-case'
+alias bc='bc --quiet --standard'
+alias pwd='pwd -P'
+alias ghci='ghci -v0'
+alias grep='grep --ignore-case --color=auto'
+
+# Convenience
+alias q='exit'
+alias md='mkdir --verbose --parents'
+alias rd='rmdir --verbose'
+alias vi='nvim'
+alias ls='eza --git --no-permissions --octal-permissions --group-directories-first'
+alias py='python -i "$MY_DOTFILES_REPO/configs/python/startup.py"'
+alias ns='newsboat'
+alias jr='journalctl --pager-end'
+alias calendar='cal --monday $(date +%Y)'
+alias memcheck='valgrind --leak-check=full --show-leak-kinds=all --show-error-list=yes'
+alias ..='cd ..'
+alias ...='cd ../..'
+alias ....='cd ../../..'
+alias .....='cd ../../../..'
+alias ......='cd ../../../../..'
+
+PS1='$ ' # Primary prompt
+PS2='> ' # Continuation prompt
+
+# XDG base directories
+export XDG_CONFIG_HOME=${HOME}/.config
+export XDG_CACHE_HOME=${HOME}/.cache
+export XDG_DATA_HOME=${HOME}/.local/share
+export XDG_STATE_HOME=${HOME}/.local/state
+
+# Do not log duplicate or exit commands
+export HISTCONTROL=ignoredups
+export HISTIGNORE=q:exit
+
+# No history file size limit
+export HISTSIZE=-1
+
+# Add scripts and local binaries to $PATH
+export PATH=${MY_DOTFILES_REPO}/scripts:${HOME}/.local/bin:${PATH}
+
+# Default programs
+export EDITOR=/usr/bin/nvim
+export SUDO_EDITOR=/usr/bin/vim
+export BROWSER=/usr/bin/qutebrowser
+
+# Miscellaneous configuration
+export LESSHISTFILE=/dev/null
+export SQLITE_HISTORY=/dev/null
+export WATCH_INTERVAL=0.5
+export MANROFFOPT="-P -c"
+export MANPAGER="less --color=d+r --color=u+b"
+export LESS="--incsearch --ignore-case --jump-target=.3 --chop-long-lines --clear-screen --use-color --RAW-CONTROL-CHARS"
+export FZF_DEFAULT_OPTS="--cycle --no-mouse --scroll-off=10 --color=gutter:-1 --keep-right     \
+    --tiebreak=begin,length --preview='file-preview {}' --preview-window=hidden                \
+    --bind=ctrl-c:cancel,ctrl-a:toggle-preview,ctrl-r:change-preview-window\(down,30%\|right\) \
+    --bind=ctrl-w:forward-word,ctrl-b:backward-word,ctrl-l:forward-char,ctrl-h:backward-char   \
+    --bind=ctrl-g:first,ctrl-u:half-page-up,ctrl-d:half-page-down                              \
+    --bind=ctrl-p:preview-half-page-up,ctrl-n:preview-half-page-down"
+
+GPG_TTY=$(tty)
+export GPG_TTY
+
+# Tell programs not to pollute $HOME
+export HISTFILE=${XDG_STATE_HOME}/bash/history
+export XAUTHORITY=${XDG_RUNTIME_DIR}/Xauthority
+export WINEPREFIX=${XDG_DATA_HOME}/wineprefixes/default
+export CARGO_HOME=${XDG_DATA_HOME}/cargo
+export RUSTUP_HOME=${XDG_DATA_HOME}/rustup
+export GHCUP_INSTALL_BASE_PREFIX=${XDG_DATA_HOME}
+export GHCUP_USE_XDG_DIRS=yes
+export CUDA_CACHE_PATH=${XDG_CACHE_HOME}/nv
+export INPUTRC=${MY_DOTFILES_REPO}/configs/readline/inputrc
+export XINITRC=${MY_DOTFILES_REPO}/configs/x/xinitrc
+
+# Make and change directory (mkdir + cd)
+mc () {
+    [ $# = 1 ] || exit 1
+    [ ! -d "$1" ] && mkdir --parents -- "$1" && echo "Created $1"
+    builtin cd -- "$1" && echo "Moved to $1"
+}
+
+# Mimic `command` completion for `on-compilation-trigger`
+command -v _command >/dev/null && complete -F _command on-compilation-trigger
+
+_my_shell_set_line () {
+    READLINE_LINE=$1; READLINE_POINT=${#1}
+}
+
+_my_shell_fzf () {
+    fzf --height=40% --layout=reverse --border=rounded "$@"
+}
+
+_my_shell_history () {
+    _my_line=$(builtin history | cut --characters=8- | _my_shell_fzf --tac --no-sort) && _my_shell_set_line "${_my_line}"
+}
+
+_my_shell_find_file () {
+    _my_file=$(_my_shell_fzf --walker=file,dir,hidden --walker-root="$1") && _my_shell_set_line "${READLINE_LINE}\"${_my_file}\" "
+}
+
+_my_shell_cd () {
+    _my_dir=$(_my_shell_fzf --walker=dir,hidden --walker-root="$1") && builtin cd -- "${_my_dir}" || return
+}
+
+# Custom fzf shell integration
+bind -m vi-insert -x '"\C-r": _my_shell_history'
+bind -m vi-insert -x '"\C-f": _my_shell_find_file .'
+bind -m vi-insert -x '"\C-g": _my_shell_find_file /'
+bind -m vi-insert -x '"\C-e": _my_shell_cd .'
+bind -m vi-insert -x '"\C-a": _my_shell_cd /'
diff --git a/scripts/bookmark-add b/scripts/bookmark-add
--- a/scripts/bookmark-add
+++ b/scripts/bookmark-add
@@ -1,33 +1,26 @@
 #!/bin/sh
 
 # $1: Message
-notify () {
-    notify-send --expire-time=2000 "bookmark-add" "$1"
-}
+notify () { command notify "bookmark-add" "$1"; }
+
+# $1: Message
+error () { notify "Error: $1"; exit 1; }
 
 selection=$(xclip -out -rmlastnl)
 if [ -n "${selection}" ]; then
     notify "Current selection: ${selection}"
 else
-    notify "Error: No selection"
-    exit 1
+    error "No selection"
 fi
 
-bookmarks="${HOME}/misc/bookmarks"
-if [ ! -e "${bookmarks}" ]; then
-    notify "Error: Bookmarks directory not found"
-    exit 1
-fi
+bookmarkdirectory=${HOME}/misc/bookmarks
+[ -d "${bookmarkdirectory}" ] || error "${bookmarkdirectory} does not exist"
+bookmarkname=$(find "${bookmarkdirectory}" -type f -printf "%f\\n" | dmenu -i -p "Save where?")
+[ -n "${bookmarkname}" ] || error "No bookmark file selected"
 
-bookmarkfile=$(find "${bookmarks}" -type f -printf "%f\\n" | dmenu -i -p "Save where?")
-if [ -z "${bookmarkfile}" ]; then
-    notify "No bookmark file selected"
-    exit 1
-fi
-
-if grep --quiet --fixed-strings --line-regexp "${selection}" "${bookmarks}/${bookmarkfile}"; then
+if grep --quiet --fixed-strings --line-regexp "${selection}" "${bookmarkdirectory}/${bookmarkname}"; then
     notify "Already bookmarked"
 else
-    echo "${selection}" >> "${bookmarks}/${bookmarkfile}"
-    notify "Bookmark saved to ${bookmarkfile}"
+    echo "${selection}" >> "${bookmarkdirectory}/${bookmarkname}"
+    notify "Bookmark saved to ${bookmarkname}"
 fi
diff --git a/scripts/bookmark-open b/scripts/bookmark-open
--- a/scripts/bookmark-open
+++ b/scripts/bookmark-open
@@ -1,11 +1,9 @@
 #!/bin/sh
 
 # $1: Message
-notify () {
-    notify-send --expire-time=2000 "bookmark-open" "$1"
-}
+error () { notify "bookmark-open" "Error: $1"; exit 1; }
 
-# $1: String to examine
+# $1: String
 looks_like_a_url () {
     case $1 in
         "https://"*) true;;
@@ -14,43 +12,25 @@ looks_like_a_url () {
     esac
 }
 
-bookmarks="${HOME}/misc/bookmarks"
-if [ ! -e "${bookmarks}" ]; then
-    notify "Error: Bookmarks directory not found"
-    exit 1
-fi
+bookmarkdirectory=${HOME}/misc/bookmarks
+[ -d "${bookmarkdirectory}" ] || error "Bookmark directory does not exist: '${bookmarkdirectory}'"
 
-filechoices=$(echo "[all]" && find "${bookmarks}" -type f -printf "%f\\n")
-bookmarkfile=$(echo "${filechoices}" | dmenu -i -p "Which bookmark file?")
-
-if [ -z "${bookmarkfile}" ]; then
-    notify "No bookmark file selected"
-    exit 1
-fi
+options=$(echo "[all]" && find "${bookmarkdirectory}" -type f -printf "%f\\n")
+bookmarkfile=$(echo "${options}" | dmenu -i -p "Which bookmark file?")
+[ -n "${bookmarkfile}" ] || error "No bookmark file selected"
 
 if [ "${bookmarkfile}" = "[all]" ]; then
-    bookmarklist=$(cat "${bookmarks}"/*)
-elif [ -e "${bookmarks}/${bookmarkfile}" ]; then
-    bookmarklist=$(cat "${bookmarks}/${bookmarkfile}")
+    bookmarklist=$(cat "${bookmarkdirectory}"/*)
+elif [ -f "${bookmarkdirectory}/${bookmarkfile}" ]; then
+    bookmarklist=$(cat "${bookmarkdirectory}/${bookmarkfile}")
 else
-    notify "Error: Bookmark file \"${bookmarkfile}\" does not exist"
-    exit 1
+    error "Bookmark file does not exist: '${bookmarkfile}'"
 fi
 
-bookmarkchoice=$(echo "${bookmarklist}" | dmenu -i -l 5)
-if [ -z "${bookmarkchoice}" ]; then
-    notify "No bookmark selected"
-    exit 1
-fi
+choice=$(echo "${bookmarklist}" | dmenu -i -l 5) || error "No bookmark selected"
 
-if looks_like_a_url "${bookmarkchoice}" && prompt-yesno "Open in browser?"; then
-    if [ -n "${BROWSER}" ]; then
-        "${BROWSER}" "${bookmarkchoice}"
-    else
-        notify "Error: \$BROWSER is not defined"
-        exit 1
-    fi
+if looks_like_a_url "${choice}"; then
+    handle-url "${choice}"
 else
-    printf %s "${bookmarkchoice}" | xclip -selection clipboard
-    notify "Copied bookmark to clipboard"
+    clip "${choice}"
 fi
diff --git a/scripts/configure-monitors b/scripts/configure-monitors
--- a/scripts/configure-monitors
+++ b/scripts/configure-monitors
@@ -1,20 +1,37 @@
 #!/bin/sh
 
-monitorfile="${MY_DOTFILES_REPO}/state/monitors"
+# $1: Message
+error () { notify "configure-monitors" "Error: $1"; exit 1; }
 
-if [ ! -f "${monitorfile}" ]; then
-    echo "Monitor file not found"
-    exit 1
-fi
+# $1: Primary monitor name
+# $2: Secondary monitor name
+auto_configure () {
+    if xrandr --listmonitors | grep --quiet --fixed-strings "$1"; then
+        xrandr --output "$1" --auto --output "$2" --off
+    fi
+}
 
-primary=$(awk "/primary/{print\$2}" "${monitorfile}")
-secondary=$(awk "/secondary/{print\$2}" "${monitorfile}")
+# $1: Primary monitor name
+# $2: Secondary monitor name
+# $3: Configuration
+configure () {
+    case $3 in
+        1)    xrandr --output "$1" --auto --output "$2" --off;;
+        2)    xrandr --output "$1" --off --output "$2" --auto;;
+        12)   xrandr --output "$1" --auto --output "$2" --auto --right-of "$1";;
+        21)   xrandr --output "$1" --auto --output "$2" --auto --left-of "$1";;
+        11)   xrandr --output "$1" --auto --output "$2" --auto --same-as "$1";;
+        auto) auto_configure "$1" "$2";;
+        *)    error "Invalid argument";;
+    esac
+}
 
-if [ -z "${primary}" ] || [ -z "${secondary}" ]; then
-    echo "Monitor file misconfigured"
-    exit 1
-fi
+monitorfile=${MY_DOTFILES_REPO}/state/monitors
+[ -f "${monitorfile}" ] || error "Monitor file not found"
 
-if xrandr --listmonitors | grep --quiet --fixed-strings "${primary}"; then
-    xrandr --output "${secondary}" --off
-fi
+# $1: primary|secondary
+monitor () {
+    awk "/$1/{print\$2}" "${monitorfile}"
+}
+
+configure "$(monitor primary)" "$(monitor secondary)" "$1"
diff --git a/scripts/dl-view b/scripts/dl-view
--- a/scripts/dl-view
+++ b/scripts/dl-view
@@ -1,36 +1,13 @@
 #!/bin/sh
 
 # $1: Message
-error () {
-    echo "Error: dl-view: $1" 1>&2
-    exit 1
-}
-
-# $1: URL
-# $2: File path without extension
-download () {
-    yt-dlp "$1"                       \
-        --sponsorblock-mark=default   \
-        --sponsorblock-remove=default \
-        --format-sort="res:720"       \
-        --output="$2"
-}
-
-# $1: URL
-run () {
-    path="/tmp/dl-view-$(date +%s)"
-    if download "$1" "${path}"; then
-        # Wildcards match the file extension
-        mpv "${path}"*
-        rm "${path}"*
-    else
-        error "Could not download media"
-    fi
-}
+error () { notify "dl-view" "Error: $1"; exit 1; }
 
 case $1 in
     "https://"*)
-        run "$1";;
+        id=$(date +%s)
+        ytdl --output="/tmp/%(title)s dl-view-${id}.%(ext)s" -- "$1"
+        mpv -- /tmp/*"dl-view-${id}"* || error "Unable to download media";;
     *)
         error "No URL given";;
 esac
diff --git a/scripts/handle-podcast-urls b/scripts/handle-podcast-urls
--- a/scripts/handle-podcast-urls
+++ b/scripts/handle-podcast-urls
@@ -1,22 +1,12 @@
 #!/bin/sh
 
 # $1: Message
-error () {
-    [ -n "${DISPLAY}" ] && notify-send --expire-time=2000 "Error: handle-podcast-urls" "$1"
-    exit 1
-}
+error () { notify "handle-podcast-urls" "Error: $1"; exit 1; }
 
-gather_lines () {
-    while read -r line; do echo "${line}"; done
-}
-
-urls=$(gather_lines | urlscan --dedupe --no-browser | grep --fixed-strings ".mp3")
+urls=$(urlscan --dedupe --no-browser | grep --fixed-strings ".mp3")
 
 case $(echo "${urls}" | wc --lines) in
-    1)
-        mpv --no-audio-display "${urls}";;
-    0)
-        error "No valid URLs found";;
-    *)
-        error "Too many valid URLs found";;
+    1) mpv --no-audio-display -- "${urls}";;
+    0) error "No valid URLs found";;
+    *) error "Too many valid URLs found";;
 esac
diff --git a/scripts/headphones-control b/scripts/headphones-control
--- a/scripts/headphones-control
+++ b/scripts/headphones-control
@@ -1,31 +1,32 @@
 #!/bin/sh
 
-indexfile="${MY_DOTFILES_REPO}/state/headphones-control-index"
+indexfile=${MY_DOTFILES_REPO}/state/headphones-control-index
 mkdir --parents "${MY_DOTFILES_REPO}/state"
 [ -f "${indexfile}" ] || echo 1 > "${indexfile}"
 
-# $1: Error message
-error () {
-    if [ -n "${DISPLAY}" ]; then
-        notify-send "Error: headphones-control" "$1"
+# $1: Message
+error () { notify "headphones-control" "Error: $1"; exit 1; }
+
+# $1: Device address
+# stdout: "connect" | "disconnect"
+connection_status () {
+    if bluetoothctl devices Connected | grep --quiet --fixed-strings "$1"; then
+        echo connect
     else
-        echo "$1" 1>&2
+        echo disconnect
     fi
-    exit 1
 }
 
 # $1: "connect" | "disconnect"
 # $2: Device address
 connect_or_disconnect () {
-    if [ -z "${DISPLAY}" ]; then
-        bluetoothctl "$1" "$2"
+    [ -n "${DISPLAY}" ] && notification=$(notify-send --print-id "Attempting to ${1}...")
+    bluetoothctl --timeout=3 -- "$1" "$2"
+    [ -n "${DISPLAY}" ] || return
+    if [ "$1" = "$(connection_status "$2")" ]; then
+        notify-send --expire-time=2000 --replace-id "${notification}" "Successfully ${1}ed"
     else
-        notification=$(notify-send --print-id "Attempting to ${1}...")
-        if bluetoothctl "$1" "$2"; then
-            notify-send --expire-time=2000 --replace-id "${notification}" "Successfully ${1}ed"
-        else
-            error "Unable to $1"
-        fi
+        error "Unable to $1"
     fi
 }
 
@@ -36,12 +37,12 @@ get_info () {
 
 # $1: Index
 get_address () {
-    get_info "$1" | cut --delimiter=" " --fields=2
+    get_info "$1" | cut --delimiter=' ' --fields=2
 }
 
 # $1: Index
 get_name () {
-    get_info "$1" | cut --delimiter=" " --fields=3-
+    get_info "$1" | cut --delimiter=' ' --fields=3-
 }
 
 # $1: Index
diff --git a/scripts/media-control b/scripts/media-control
--- a/scripts/media-control
+++ b/scripts/media-control
@@ -1,10 +1,7 @@
 #!/bin/sh
 
-# $1: Error message
-error () {
-    notify-send "Error: media-control" "$1"
-    exit 1
-}
+# $1: Message
+error () { notify "media-control" "Error: $1"; exit 1; }
 
 # $@: Arguments to forward to the player
 control () {
@@ -13,25 +10,20 @@ control () {
 
 # $1: "-" | "+"
 seek () {
-    mkdir --parents "${MY_DOTFILES_REPO}/state"
-    lockfile="${MY_DOTFILES_REPO}/state/lock-media-control-seek"
+    lockfile=/tmp/dotfiles-media-control-seek-lock
     [ -f "${lockfile}" ] && return
     touch "${lockfile}"
     case $(control status) in
-        Paused)
-            control position "20$1";;
-        Playing)
-            control position "5$1";;
-        *)
-            error "Invalid player state";;
+        Paused)  control position "20$1";;
+        Playing) control position "5$1";;
+        *)       error "Invalid player state";;
     esac
     sleep 0.5
     rm "${lockfile}"
 }
 
 toggle () {
-    mkdir --parents "${MY_DOTFILES_REPO}/state"
-    lockfile="${MY_DOTFILES_REPO}/state/media-control-toggle-lock"
+    lockfile=/tmp/dotfiles-media-control-toggle-lock
     if [ -f "${lockfile}" ]; then
         playerctl --all-players pause &
         bluetoothctl disconnect &
@@ -42,7 +34,7 @@ toggle () {
             sleep 1
             rm "${lockfile}"
         } &
-        if [ "$(control status)" = "Paused" ]; then
+        if [ "$(control status)" = Paused ]; then
             control position 5-
             control play
         else
@@ -52,7 +44,7 @@ toggle () {
 }
 
 show_current_track_title () {
-    [ -z "${DISPLAY}" ] && return
+    [ -n "${DISPLAY}" ] || return
     if title=$(control metadata title); then
         notify-send --replace-id=999999999 --expire-time=750 "Now playing" "${title}"
     fi
@@ -77,16 +69,10 @@ next () {
 }
 
 case $1 in
-    play|pause)
-        toggle;;
-    next)
-        next;;
-    previous)
-        previous;;
-    forward)
-        seek +;;
-    rewind)
-        seek -;;
-    *)
-        error "Invalid argument";;
+    toggle|play|pause) toggle;;
+    next)              next;;
+    previous)          previous;;
+    forward)           seek +;;
+    rewind)            seek -;;
+    *)                 error "Invalid argument";;
 esac
diff --git a/scripts/run-tests b/scripts/run-tests
--- a/scripts/run-tests
+++ b/scripts/run-tests
@@ -1,10 +1,7 @@
 #!/bin/sh
 
 # $1: Message
-error () {
-    echo "Error: run-tests: $1" 1>&2
-    exit 1
-}
+error () { notify "run-tests" "Error: $1"; exit 1; }
 
 # $1: Directory
 run_tests () {
@@ -18,10 +15,7 @@ run_tests () {
 }
 
 case $# in
-    0)
-        run_tests .;;
-    1)
-        run_tests "$1";;
-    *)
-        error "Too many arguments";;
+    0) run_tests .;;
+    1) run_tests "$1";;
+    *) error "Too many arguments";;
 esac
