Update
- Add shellcheck configuration
- Improve scripts according to shellcheck suggestions

diff --git a/scripts/headphones-control b/scripts/headphones-control
--- a/scripts/headphones-control
+++ b/scripts/headphones-control
@@ -1,9 +1,13 @@
 #!/bin/sh
 
+indexfile="${MY_DOTFILES_REPO}/state/headphones-control-index"
+mkdir --parents "${MY_DOTFILES_REPO}/state"
+[ -f "${indexfile}" ] || echo 1 > "${indexfile}"
+
 # $1: Error message
 error () {
-    if [ -n "$DISPLAY" ]; then
-        notify-send "Error: toggle-headphones" "$1"
+    if [ -n "${DISPLAY}" ]; then
+        notify-send "Error: headphones-control" "$1"
     else
         echo "$1" 1>&2
     fi
@@ -13,32 +17,46 @@ error () {
 # $1: "connect" | "disconnect"
 # $2: Device address
 connect_or_disconnect () {
-    if [ -z "$DISPLAY" ]; then
+    if [ -z "${DISPLAY}" ]; then
         bluetoothctl "$1" "$2"
     else
         notification=$(notify-send --print-id "Attempting to ${1}...")
         if bluetoothctl "$1" "$2"; then
-            notify-send --expire-time=2000 --replace-id "$notification" "Successfully ${1}ed"
+            notify-send --expire-time=2000 --replace-id "${notification}" "Successfully ${1}ed"
         else
             error "Unable to $1"
         fi
     fi
 }
 
-find_device () {
-    for deviceaddress in $(bluetoothctl devices | cut -d' ' -f2); do
-        deviceinfo=$(bluetoothctl info "$deviceaddress")
-        echo "$deviceinfo" | grep -q -x "\s*Paired: yes"         || continue
-        echo "$deviceinfo" | grep -q -x "\s*Alias: myheadphones" || continue
-        echo "$deviceaddress"
-        return
-    done
-    error "No headphones available"
+get_index () {
+    cat "${indexfile}"
+}
+
+# $1: Index
+rotate_index () {
+    case $1 in
+        1) echo 2;;
+        2) echo 1;;
+        *) error "Invalid device index";;
+    esac
+}
+
+# $1: New index
+update_index () {
+    [ -n "${DISPLAY}" ] && notify-send --expire-time=2000 "headphones-control" "New headphones index: $1"
+    echo "$1" > "${indexfile}"
+}
+
+get_address () {
+    bluetoothctl devices Paired | cut -d' ' -f2 | sed --quiet "$(get_index)p"
 }
 
 case $1 in
     connect|disconnect)
-        connect_or_disconnect "$1" "$(find_device)";;
+        connect_or_disconnect "$1" "$(get_address)";;
+    rotate)
+        update_index "$(rotate_index "$(get_index)")";;
     *)
-        error "Invalid argument";
+        error "Invalid argument";;
 esac
