Config update

diff --git a/scripts/run-tests b/scripts/run-tests
--- a/scripts/run-tests
+++ b/scripts/run-tests
@@ -2,7 +2,7 @@
 
 # $1: Message
 error () {
-    echo "Error: run-tests: $1"
+    echo "Error: run-tests: $1" 1>&2
     exit 1
 }
 
@@ -17,10 +17,10 @@ run_tests () {
     fi
 }
 
-case "$#" in
-    "0")
+case $# in
+    0)
         run_tests .;;
-    "1")
+    1)
         run_tests "$1";;
     *)
         error "Invalid argument count";;
