Improve some scripts by removing need for state files
- Use `setxkbmap -query` for keyboard state
- Use `bluetoothctl devices` for bluetooth device addresses

diff --git a/scripts/toggle-headphones b/scripts/toggle-headphones
--- a/scripts/toggle-headphones
+++ b/scripts/toggle-headphones
@@ -2,19 +2,33 @@
 
 error () {
     notify-send "Error: toggle-headphones" "$1"
-    error 1
+    exit 1
 }
 
-addressfile="$MY_DOTFILES_REPO/state/headphones-address"
-[ ! -e "$addressfile" ] && error "Headphones address file not found"
+connect_or_disconnect () {
+    notification=$(notify-send --print-id "Attempting to $1...")
+    if bluetoothctl "$1" "$2"
+    then
+        notify-send --replace-id "$notification" "Successfully $1ed"
+    else
+        error "Unable to $1"
+    fi
+}
 
-headphones=$(cat "$addressfile")
+for deviceaddress in $(bluetoothctl devices | cut -d' ' -f2)
+do
+    deviceinfo=$(bluetoothctl info "$deviceaddress")
+    echo "$deviceinfo" | grep -q -x "\s*Paired: yes"         || continue
+    echo "$deviceinfo" | grep -q -x "\s*Alias: myheadphones" || continue
+    case "$(echo "$deviceinfo" | grep -F "Connected" | awk '{print $2}')" in
+        yes)
+            connect_or_disconnect "disconnect" "$deviceaddress";;
+        no)
+            connect_or_disconnect "connect" "$deviceaddress";;
+        *)
+            error "Unable to interpret bluetoothctl output";;
+    esac
+    exit 0
+done
 
-case "$(bluetoothctl info "$headphones" | grep Connected)" in
-  *yes*)
-      bluetoothctl disconnect "$headphones";;
-  *no*)
-      bluetoothctl connect "$headphones";;
-  *)
-      error "Invalid bluetoothctl output";;
-esac
+error "No headphones available"
